version: '3'

services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      DB_SERVER: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db


  db:
    build: 
      context: ./db
      dockerfile: dockerfile
    ports:
        - 1434:1434